name: Update public content to main jekyll site

env:
    SOURCE_POSTS_LOCATION: "_posts"
    DESTINATION_POSTS_LOCATION: "_posts_temp/public"
    DESTINATION_BRANCH:  ${{ github.head_ref || github.ref_name }} #name of the branch which triggered the workflow
    DESTINATION_REPO: "QED-DeveloperPortal/qed-developer-portal"   
    GITHUB_USER_NAME: "qed-devportal-admin"
    GITHUB_USER_EMAIL: "developerportal@qed.qld.gov.au"

on:
    push:
        branches:
            - master
            - dev 
            - beta
            - test
        paths:
            - "_posts/**"

permissions:
  contents: write

jobs:   
  update-public-content:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source repository
              uses: actions/checkout@v3
              with: 
                submodules: true 
                fetch-depth: 0

            - name: ListFolderContents
              run: ls -laR ${{ env.SOURCE_POSTS_LOCATION }}

            - name: List changed files
              run: |
                changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
                echo "Changed files: $changed_files"           

            - name: Checkout destination repository
              uses: actions/checkout@v3
              with:
                  repository:  ${{ env.DESTINATION_REPO }}
                  path: ${{ env.DESTINATION_REPO}}

            - name: Copy updated files
              run: |
                IFS=$'\n'
                for file in $(echo "${{ steps.check_changes.outputs.files }}"); do
                  mkdir -p  ${{ env.DESTINATION_REPO }}/"$(dirname "$file")"
                  cp "$file" ${{ env.DESTINATION_REPO }}/"$file"
                done

            - name: Commit and push changes
              run: |
                cd  ${{ env.DESTINATION_REPO }}
                git config user.name ${{ env.GITHUB_USER_NAME }}
                git config user.email ${{ env.GITHUB_USER_EMAIL }}
                git add .
                git commit -m "[GHA] Testing - Push public content to Developer Portal site"
                git push
          